name: Deploy Complex
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      
      - name: build react test image
        run: docker build -f ./client/Dockerfile.dev -t ginsuarez/react-test ./client
      
      - name: run react-test on container
        run: docker run -e CI=true ginsuarez/react-test npm test

      - name: build production client
        run: docker build -t ginsuarez/multi-client ./client

      - name: build production nginx
        run: docker build -t ginsuarez/multi-nginx ./nginx

      - name: build production server
        run: docker build -t ginsuarez/multi-server ./server

      - name: build production worker
        run: docker build -t ginsuarez/multi-worker ./worker 

      - name: docker cli login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: push client image to docker hub
        run: docker push ginsuarez/multi-client

      - name: push nginx image to docker hub
        run: docker push ginsuarez/multi-nginx

      - name: push server image to docker hub
        run: docker push ginsuarez/multi-server
      
      - name: push worker image to docker hub
        run: docker push ginsuarez/multi-worker

      - name: Deployment package
        run: zip -r deploy.zip . -x '*.git*'      

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment: 'Multidocker-env'
          existing_bucket_name: elasticbeanstalk-us-east-2-652178207511
          version_label: ${{ github.sha }}
          region: us-east-2
          deployment_package: deploy.zip
